Youtube Videos Company Pages
parameter1/rogue-monkey-media-websites pull request #14
Opened 2021-11-08 16:50 UTC by Shinsina

<img width="1920" alt="Screen Shot 2021-11-08 at 10 47 22 AM" src="https://user-images.githubusercontent.com/46794001/140783812-7d977f51-60a1-4b45-9e02-7f0ae9444ed1.png">

2021-11-08 16:51 UTC, Shinsina commented
![](https://github.trello.services/images/mini-trello-icon.png) [Update Resource Guide layout](https://trello.com/c/2K410y8k/23-update-resource-guide-layout)

2021-12-15 14:50 UTC, B77Mills requested changes

2021-12-15 14:50 UTC, B77Mills commented on packages/global/components/layouts/content/company.marko
> -        <marko-web-query|{ nodes }|
@Shinsina I believe this needs to be added back in

2021-12-15 15:31 UTC, B77Mills approved these changes

2021-12-15 15:31 UTC, merged